language: rust
sudo: false

env:
  global:
    - secure: O9dRL7LTjFXvShTmAIGe3vcT5AKwEH/6zGzhN7G2lCSEl4PDxAknjDHsQUcl2WtRSjw1xxT6krdL3sQ2gTNVdvuZwhA9OASbQWxQTLc4KzI7YFJgZv7P+Hvm3vH0kui8jQm1h7kwu1c3xpUT2vh2y/Ymv7NwcYz/Ek00o9JoM/Q=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
