language: rust
sudo: false

env:
  global:
    - secure: PphcilRrRz+PMqMTnrbkWZr83avdFMINCR/VsZcjPpCcSwHnWYZWqEdVcaO4HbUvFmTmPuDLOPqVxN4g8EwuQNB9huLBTkPamuh4A3CHbqp8GIkzKLfS7rtqdJQakeqXczukXqrs6NZDIE59SBAtSshW4SR7hjh8Skxo9027tmo=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
