[package]

name = "seq"
version = "0.0.0"
authors = ["Jorge Aparicio <japaric@linux.com>"]

[dependencies.collect]
git = "https://github.com/gankro/collect-rs"

[dependencies.seq_macros]
path = "macros"

[profile.dev]
debug = false

[profile.test]
debug = false
